name: CI
on: push
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build & test JAR with Gradle
        run: ./gradlew test
